# Generated by Django 4.1 on 2023-11-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comoencasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=50)),
                ('desc_plato', models.CharField(max_length=80)),
                ('precio_plato', models.FloatField()),
            ],
        ),
    ]
