# Generated by Django 4.1 on 2023-11-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comoencasa', '0005_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='direcciones',
            field=models.ManyToManyField(blank=True, to='app_comoencasa.direccion'),
        ),
    ]
