# Generated by Django 4.1 on 2023-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=120)),
                ('ciudad', models.CharField(max_length=50)),
                ('codigo_postal', models.IntegerField()),
                ('nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('pedidos', models.ManyToManyField(related_name='clientes', to='app_comoencasa.pedido')),
            ],
        ),
    ]
