# Generated by Django 4.1 on 2023-11-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comoencasa', '0007_carrito_itemcarrito_remove_perfilusuario_direcciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='mensaje',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itemcarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
